### ISSUE TITLE
Customizing the output of redux actions

### ISSUE THREAD

**Issue by chaffneue** [mikestead/openapi-client#22]
Hey there! I've been investigating a number of different ways to integrate swagger with our React+Redux app and this library is looking pretty good.  Looking at some of the alternative generators like https://github.com/swagger-api/swagger-codegen and https://www.npmjs.com/package/swagger-js-codegen, they seem to offer some form of template extensibility through Mustache templates. I'm wondering if that's something you considered for this design and if not, how can I control what is generated especially for the redux actions side of things?

**Comment by mikestead** [comment]
@chaffneue Thanks for the positive feedback and questions.

`Mustache` was the approach I originally took, but one of my main remits when writing this was to have output that looked human written and not code generated. I couldn't get that level of control and quality from my attempts with Mustache or Handlebars so I went a more hand crafted path. The downside of that is that it's not quite as easy to customize / override.

Your best bet if you want to do something super custom is to fork. If there's something you feel could come back into here and be of benefit then I'm open to improvements.

FYI The redux actions are generated from this module `https://github.com/mikestead/openapi-client/blob/master/src/gen/js/genReduxActions.ts`

**Comment by chaffneue** [comment]
Great info! Thanks for the help.
