### ISSUE TITLE
redux action params are not converted to camelCase

### ISSUE THREAD

**Issue by pgr86** [mikestead/openapi-client#38]
First off all, thanks for this great project! I'm really happy to get all the API stuff and even the redux actions generated :-)

I found a small bug within the generated redux action code.

Our API consumes a user token via http header - we call it 'X-token'.
This is a mandatory param for our action.

The code generation will output something like this:

```javascript
export function createUser(XToken, options, info) {
  return dispatch => {
    dispatch({ type: CREATE_USER_START, meta: { info } })
    return user.createUser(X-token, options)
      .then(response => dispatch({
        type: CREATE_USER,
        payload: response.data,
        error: response.error,
        meta: {
          res: response.raw,
          info
        }
      }))
  }
}
```

The param in the exported function will be correctly transformed from 'X-token' to XToken, but within the return statement the param name gets not transformed in this way. This will obviously throw an error.

I created a pull request #37 for that.

**Comment by mikestead** [comment]
Thanks, PR #37 merged and released under `v1.0.2`
