### ISSUE TITLE
Make fetch'es 'credentials option' avail. 

### ISSUE THREAD

**Issue by sebs** [mikestead/openapi-client#41]
In my setup, I need to use "credentials = true" as option to fetch, in order to work with cookie based auth. Its as easy as change the makeRequest method, but it would be fine to be able to "pass it in", not change the gateway/index.js "by hand"

**Comment by mikestead** [comment]
Hey @sebs, this is actually available via `gateway.init` [options](https://github.com/mikestead/openapi-client/blob/master/src/gen/js/genTypes.ts#L166) as prop `fetchOptions`, here's an e.g.

```javascript
serviceGateway.init({
  fetchOptions: {
    mode: 'cors',
    credentials: 'same-origin'
  };
});
```
Apologies this needs some docs added to readme.

**Comment by mikestead** [comment]
Add some [docs here](https://github.com/mikestead/openapi-client#initialization-options)

**Comment by sebs** [comment]
Thanks
