### ISSUE TITLE
The models are also generated ?

### ISSUE THREAD

**Issue by danysz** [mikestead/openapi-client#52]
I have a server which is OpenAPI v3.0 compatible.

I tried to generate the functions and it worked. Looking into the code I see that I will have to write the "models" by myself. Is it in purpose or because some issue the "models" are not generated ?

**Comment by mikestead** [comment]
Hi @danysz openapi-client is not currently compatible with OpenAPI 3. The spec changed quite a bit so models are defined in a different location and the schemas for params which tie to functions are also somewhat different. I wouldn't really trust code generated using this tool against v3 spec.
